### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fstxz** [gildedhipbone/prop_painter#2]
Hi there. I would like to continue working on this project, but the GPL license will make it hard for others to use this addon in their projects (unless their project is also licensed under GPL, which is highly unlikely as the majority of games are proprietary).

As you are the only contributor, you have the ability to change the license to whatever you want. Most Godot plugins are licensed under MIT, so I would chose that.

**Comment by gildedhipbone** [comment]
Hi there!
First off, sorry for being so inactive and slow to respond.
Second, I will update the license to MIT. In the meanwhile, consider this comment my approval to do whatever you want with the project.

**Comment by fstxz** [comment]
Thank you very much!!
